# Site settings
title: Unforgettable Road Trips
client:
  name: Michelin
  link: https://www.michelin.co.uk/?utm_source=secretescapes&utm_medium=hub&utm_content=brd_&utm_campaign=notpredef_brand_notpredef_secretescapes&utm_term=_logo
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Wild coastlines, epic mountain landscapes and beguiling countryside await in our road&#8209;trip guides, ready to test your motoring skills. Twists, turns, hairpins and breathtaking panorama awaits, interspersed with remarkable stop-offs and unmissable&nbsp;moments. 

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/unforgettable-road-trips" # the subpath of your site, e.g. /blog/
img:     "/unforgettable-road-trips/_assets/img"
css:     "/unforgettable-road-trips/_assets/css"
js:      "/unforgettable-road-trips/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed